export * from './comment.schema';
export * from './coupon.schema';
export * from './course.schema';
export * from './history.schema';
export * from './lecture.schema';
export * from './lesson.schema';
export * from './order.schema';
export * from './rating.schema';
export * from './user.schema';
