export { default as IconClock } from "./IconClock";
export { default as IconComment } from "./IconComment";
export { default as IconExplore } from "./IconExplore";
export { default as IconEye } from "./IconEye";
export { default as IconOrder } from "./IconOrder";
export { default as IconPlay } from "./IconPlay";
export { default as IconStar } from "./IconStar";
export { default as IconStudy } from "./IconStudy";
export { default as IconUsers } from "./IconUsers";
